node {
    def app
    stage('Checkout git repo') {
      git branch: 'master', url: params.git_repo
    }
        
    
    stage('Build image') {
        echo "estoy aqui"
        app = docker.build("jcendejas/appdockerlnx:dev", '"C:/Program Files (x86)/Jenkins/workspace/AppDockerLnx" -f "C:/Program Files (x86)/Jenkins/workspace/AppDockerLnx/AppDockerLnx/Dockerfile" ')
        echo "termine aqui aqui"
        
    }
    
    
    stage('Push image') {
    withCredentials([usernamePassword( credentialsId: 'DockerHUB', usernameVariable: 'USER', passwordVariable: 'PASSWORD')]) {
        def registry_url = "registry.hub.docker.com/"
        bat "docker login -u $USER -p $PASSWORD ${registry_url}"
        docker.withRegistry("http://${registry_url}", "DockerHUB") {
            // Push your image now
              bat "docker push jcendejas/appdockerlnx:dev"
            
     
        }
    }
        
     stage('run image') {
        bat "docker ps -q --filter name=appdockerlnx && docker stop appdockerlnx && docker rm -fv appdockerlnx"
        bat "docker login -u jcendejas -p 136369Ctj"
        bat "docker run -p 6060:80 --name appdockerlnx -d jcendejas/appdockerlnx:dev"
        bat "docker network connect pvn_sp_is appdockerlnx "
         
        
    }
}
    




   
}
